
// What is REPL?
// REPL stand for Read, Eval , Print,Loop .
// It represent a computer environment.It is similar to unix shell in which a command is entered. 
// Then the system respond with an output.

// How to enter in repl i terminal?
// Use command "node"

// What expresion Repl handel?
// 1. Js Experssion
// 9/3,9%3,3+4

// 2.use variablea
// var a = 'chanchal'
// var b = 'verma'
// a+b = 'chanchalverma'

//  3.Multiline code/loops
// var x = 0
// do
// {
//  x++;
//  console.log(`my x value is ${x}`)
//  }
//  while(x<5);

// 4.use (_) to get the last result
// _ use to check last result
// 5+5
// 10
//  10+5
// 15
// 15+5
// 20
//  _
// 20
//  _+5
// 25

// 5.we can use editor mode.

// .editor
// Entering editor mode (Ctrl+D to finish, Ctrl+C to cancel)
// const name = (myname)=>{console.log(`my name is ${myname}`)}
// name('Nisha')

//  Output 
// my name is Nisha